apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 1
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: api
        image: us-central1-docker.pkg.dev/liatrio-interview-26042023/docker-images/api:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080