apiVersion: apps/v1
kind: Deployment
spec:
  containers:
  - name: liatrio-demo
    image: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPO }}/${{ vars.IMAGE }}:$GITHUB_SHA
    ports:
    - containerPort: 8080
    env:
      - name: PORT
        value: "8080"

apiVersion: v1
kind: Service        
spec:
  type: LoadBalancer
  selector:
    app: liatrio-demo
  ports:
  - port: 8080
    targetPort: 8080        