name: Build jar and upload to artifact registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEPLOYMENT: liatrio-demo
  TAG: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPO }}/${{ vars.IMAGE }}

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.TF_API_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file api/pom.xml

    - name: gcloud auth
      run: gcloud --quiet auth configure-docker us-central1-docker.pkg.dev
    
    - name: gcloud k8s plugin install
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Build Docker image
      run: docker build --file Dockerfile --tag "$TAG:$GITHUB_SHA" .

    - name: Publish
      run: docker push "$TAG:$GITHUB_SHA"

    - name: k8s auth
      run: gcloud container clusters get-credentials simple-autopilot-private-cluster --region ${{ vars.REGION }}

    - name: create deployment
      run: kubectl create deployment $DEPLOYMENT --image=$TAG:$GITHUB_SHA

    - name: expose service
      run: kubectl expose deployment $DEPLOYMENT --name=$DEPLOYMENT-service --type=LoadBalancer --port 8080 --target-port 8080

#    - name: Service
#      run: kubectl apply -f Service.yaml

#    - name: Deployment
#      run: kubectl apply -f Deployment.yaml