name: Build jar, upload to artifact registry, deploy to k8s

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEPLOYMENT: liatrio-demo
  CLUSTER: simple-autopilot-cluster
  REPO: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPO }}/${{ vars.IMAGE }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.TF_API_TOKEN }}

    - name: add package manager
      run: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    - name: package cert
      run: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    - name: update
      run: sudo apt-get update
    - name: install plugin
      run: sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file api/pom.xml

    - name: gcloud auth
      run: gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: docker build --file Dockerfile -t "$REPO:$GITHUB_SHA" -t "$REPO:latest" .

    - name: Publish
      run: docker push --all-tags "$REPO"

    - name: k8s auth
      run: gcloud container clusters get-credentials $CLUSTER --region ${{ vars.REGION }}

    - name: apply deployment
      run: kubectl apply -f deployment.yaml

    - name: apply service
      run: kubectl apply -f service.yaml
