name: Build jar and upload to artifact registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEPLOYMENT: liatrio-demo
  TAG: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPO }}/${{ vars.IMAGE }}

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.TF_API_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file api/pom.xml

    - run: gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: docker build --file Dockerfile --tag "$TAG:$GITHUB_SHA" .

    - name: Publish
      run: docker push "$TAG:$GITHUB_SHA"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set $TAG:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide

#    - name: Service
#      run: kubectl apply -f Service.yaml

#    - name: Deployment
#      run: kubectl apply -f Deployment.yaml